"""add summary and verdict to reviews

Revision ID: 543658ef2f15
Revises: ec0c1f716b6c
Create Date: 2026-07-15 11:35:08.573323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '543658ef2f15'
down_revision: Union[str, None] = 'ec0c1f716b6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('reviews', sa.Column('verdict', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'verdict')
    op.drop_column('reviews', 'summary')
    # ### end Alembic commands ###
