"""add review duration_ms

Revision ID: 724d350726fa
Revises: c5793413e749
Create Date: 2026-07-29 21:39:12.308454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '724d350726fa'
down_revision: Union[str, None] = 'c5793413e749'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('duration_ms', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'duration_ms')
    # ### end Alembic commands ###
