"""add review queued_at and total_ms

Revision ID: e381a8478c7f
Revises: 724d350726fa
Create Date: 2026-07-30 21:45:13.904879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e381a8478c7f'
down_revision: Union[str, None] = '724d350726fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('total_ms', sa.Integer(), nullable=True))
    op.add_column('reviews', sa.Column('queued_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'queued_at')
    op.drop_column('reviews', 'total_ms')
    # ### end Alembic commands ###
